DATA:
  PATH:  "./data/"

DOWNLOAD:
  PATH: "./data/"

FILE:
  ENCODING: utf_8

LOGGING:
  MAIN_PATH: "./logs/main.log"
  LEVEL: DEBUG

ETF:
  CONSTITUENTS_PATH: "./data/index/constituents/us/etf.csv"

FX:
  CONSTITUENTS_PATH: "./data/index/constituents/us/fx.csv"

NASDAQ:
  CONSTITUENTS_PATH: "./data/index/constituents/us/nasdaq.csv"
  CONSTITUENTS_URL: "https://raw.githubusercontent.com/datasets/nasdaq-listings/master/data/nasdaq-listed-symbols.csv"

SPX:
  CONSTITUENTS_PATH: "./data/index/constituents/us/spx.csv"
  CONSTITUENTS_URL: "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv"
